export const ACTION_TYPES = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  SOCIAL_LOGIN_REQUEST: 'SOCIAL_LOGIN_REQUEST',
  OTP_REQUEST: 'OTP_REQUEST',
  SET_LOGIN_DATA: 'SET_LOGIN_DATA',
  LOGOUT: 'LOGOUT',
  SIGNUP_REQUEST: 'SIGNUP_REQUEST',
  UPDATE_USER_DATA: 'UPDATE_USER_DATA',
  ACTIVE_STORE: 'ACTIVE_STORE',
  AGORA_APP_ID: 'AGORA_APP_ID',
  UPDATE_USER_LEVEL: 'UPDATE_USER_LEVEL',
  UPDATE_HOST_LEVEL: 'UPDATE_HOST_LEVEL',
  UPDATE_EDITPROFILE: 'UPDATE_EDITPROFILE',

};
